
// Configuration, Loading and Errors
export const GET_CONFIG = 'GET_CONFIG';

export const SET_LOADING = 'SET_LOADING';
export const REMOVE_LOADING = 'REMOVE_LOADING';

export const INSERT_ERROR = 'INSERT_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';



// Sidebar Menu
export const REMOVE_SELECTED_MENU = 'REMOVE_SELECTED_MENU';

export const SELECTED_STATIC_CATEGORY ='SELECTED_STATIC_CATEGORY';
export const SELECTED_GENRE = 'SELECTED_GENRE';

export const GET_GENRES_REQUEST = 'GET_GENRES_REQUEST';
export const GET_GENRES_SUCCESS = 'GET_GENRES_SUCCESS';
export const GET_GENRES_FAILURE = 'GET_GENRES_FAILURE';
export const GET_GENRES_FINISHED = 'GET_GENRES_FINISHED';

export const INVALID_MENU_SELECTION = 'INVALID_MENU_SELECTION';
export const RESET_SELECTED_MENU = 'RESET_SELECTED_MENU';



// Movie related types
export const FETCH_MOVIE = 'FETCH_MOVIE';
export const FETCH_CAST = 'FETCH_CAST';

export const FETCH_MOVIES_LOADING = 'FETCH_MOVIES_LOADING';
export const FETCH_MOVIES_FINISHED = 'FETCH_MOVIES_FINISHED';

export const FETCH_MOVIE_LOADING = 'FETCH_MOVIE_LOADING';
export const FETCH_MOVIE_FINISHED = 'FETCH_MOVIE_FINISHED';

export const FETCH_MOVIE_ERROR = 'FETCH_MOVIE_ERROR';

export const FETCH_ALL_MOVIES_REQUEST = 'FETCH_ALL_MOVIES_REQUEST';
export const FETCH_ALL_MOVIES_SUCCESS = 'FETCH_ALL_MOVIES_SUCCESS';
export const FETCH_ALL_MOVIES_FAILURE = 'FETCH_ALL_MOVIES_FAILURE';

export const FETCH_MOVIES_REQUEST = 'FETCH_MOVIES_REQUEST';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_MOVIES_FAILURE = 'FETCH_MOVIES_FAILURE';

export const FETCH_MOVIES_SEARCH_REQUEST = 'FETCH_MOVIES_SEARCH_REQUEST';
export const FETCH_MOVIES_SEARCH_SUCCESS = 'FETCH_MOVIES_SEARCH_SUCCESS';
export const FETCH_MOVIES_SEARCH_FAILURE = 'FETCH_MOVIES_SEARCH_FAILURE';

export const FETCH_MOVIES_BY_GENRE_REQUEST = 'FETCH_MOVIES_BY_GENRE_REQUEST';
export const FETCH_MOVIES_BY_GENRE_SUCCESS = 'FETCH_MOVIES_BY_GENRE_SUCCESS';
export const FETCH_MOVIES_BY_GENRE_FAILURE = 'FETCH_MOVIES_BY_GENRE_FAILURE';

export const FETCH_POPULAR_MOVIES = 'FETCH_POPULAR_MOVIES';
export const FETCH_TOP_RATED_MOVIES = 'FETCH_TOP_RATED_MOVIES';
export const FETCH_UPCOMING_MOVIES = 'FETCH_UPCOMING_MOVIES';



// User related types
export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_FINISHED = 'FETCH_USER_FINISHED';
export const FETCH_USER_LOADING = 'FETCH_USER_LOADING';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR';

export const CLEAR_USER_SUCCESS = 'CLEAR_USER_SUCCESS';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const SET_USER_LOADING = 'SET_USER_LOADING';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';

export const FETCH_USERS_SEARCH_REQUEST = 'FETCH_USERS_SEARCH_REQUEST';
export const FETCH_USERS_SEARCH_SUCCESS = 'FETCH_USERS_SEARCH_SUCCESS';
export const FETCH_USERS_SEARCH_FAILURE = 'FETCH_USERS_SEARCH_FAILURE';



// Watchlist types
export const ADD_TO_WATCHLIST_REQUEST = 'ADD_TO_WATCHLIST_REQUEST';
export const ADD_TO_WATCHLIST_SUCCESS = 'ADD_TO_WATCHLIST_SUCCESS';
export const ADD_TO_WATCHLIST_FAILURE = 'ADD_TO_WATCHLIST_FAILURE';

export const DELETE_FROM_WATCHLIST_REQUEST = 'DELETE_FROM_WATCHLIST_REQUEST';
export const DELETE_FROM_WATCHLIST_SUCCESS = 'DELETE_FROM_WATCHLIST_SUCCESS';
export const DELETE_FROM_WATCHLIST_FAILURE = 'DELETE_FROM_WATCHLIST_FAILURE';

export const FETCH_MOVIESPERSON = 'FETCH_MOVIESPERSON';
export const FETCH_MOVIESPERSON_LOADING = 'FETCH_MOVIESPERSON_LOADING';
export const FETCH_MOVIESPERSON_FINISHED = 'FETCH_MOVIESPERSON_FINISHED';

export const SELECTED_WATCHLIST = 'SELECTED_WATCHLIST';

export const FETCH_RECOMMENDATIONS_LOADING = 'FETCH_RECOMMENDATIONS_LOADING';
export const FETCH_RECOMMENDATIONS_FINISHED = 'FETCH_RECOMMENDATIONS_FINISHED';
export const FETCH_RECOMMENDATIONS = 'FETCH_RECOMMENDATIONS';



// For preference types
export const FETCH_ACTORS_REQUEST = 'FETCH_ACTORS_REQUEST';
export const FETCH_ACTORS_SUCCESS = 'FETCH_ACTORS_SUCCESS';
export const FETCH_ACTORS_FAILURE = 'FETCH_ACTORS_FAILURE';

export const FETCH_ACTOR_REQUEST = 'FETCH_ACTOR_REQUEST';
export const FETCH_ACTOR_SUCCESS = 'FETCH_ACTOR_SUCCESS';
export const FETCH_ACTOR_FAILURE = 'FETCH_ACTOR_FAILURE';

export const FETCH_DIRECTORS_REQUEST = 'FETCH_DIRECTORS_REQUEST';
export const FETCH_DIRECTORS_SUCCESS = 'FETCH_DIRECTORS_SUCCESS';
export const FETCH_DIRECTORS_FAILURE = 'FETCH_DIRECTORS_FAILURE';

export const FETCH_GENREPREFERENCE_REQUEST = 'FETCH_GENREPREFERENCE_REQUEST';
export const FETCH_GENREPREFERENCE_SUCCESS = 'FETCH_GENREPREFERENCE_SUCCESS';
export const FETCH_GENREPREFERENCE_FAILURE = 'FETCH_GENREPREFERENCE_FAILURE';

export const ADD_PREFERENCES_REQUEST = 'ADD_PREFERENCES_REQUEST';
export const ADD_PREFERENCES_SUCCESS = 'ADD_PREFERENCES_SUCCESS';
export const ADD_PREFERENCES_FAILURE = 'ADD_PREFERENCES_FAILURE';

export const SET_PREFERENCES = 'SET_PREFERENCES';



// Feedback types
export const ADD_FEEDBACK_REQUEST = 'ADD_FEEDBACK_REQUEST';
export const ADD_FEEDBACK_SUCCESS = 'ADD_FEEDBACK_SUCCESS';
export const ADD_FEEDBACK_FAILURE = 'ADD_FEEDBACK_FAILURE';

export const GET_FEEDBACKS_REQUEST = 'GET_FEEDBACKS_REQUEST';
export const GET_FEEDBACKS_SUCCESS = 'GET_FEEDBACKS_SUCCESS';
export const GET_FEEDBACKS_FAILURE = 'GET_FEEDBACKS_FAILURE';

export const GET_USER_FEEDBACKS_REQUEST = 'GET_USER_FEEDBACKS_REQUEST';
export const GET_USER_FEEDBACKS_SUCCESS = 'GET_USER_FEEDBACKS_SUCCESS';
export const GET_USER_FEEDBACKS_FAILURE = 'GET_USER_FEEDBACKS_FAILURE';

export const UPDATE_FEEDBACK_REQUEST = 'UPDATE_FEEDBACK_REQUEST';
export const UPDATE_FEEDBACK_SUCCESS = 'UPDATE_FEEDBACK_SUCCESS';
export const UPDATE_FEEDBACK_FAILURE = 'UPDATE_FEEDBACK_FAILURE';

export const DELETE_FEEDBACK_REQUEST = 'DELETE_FEEDBACK_REQUEST';
export const DELETE_FEEDBACK_SUCCESS = 'DELETE_FEEDBACK_SUCCESS';
export const DELETE_FEEDBACK_FAILURE = 'DELETE_FEEDBACK_FAILURE';



// Friends types
export const ADD_FRIEND_REQUEST = 'ADD_FRIEND_REQUEST';
export const ADD_FRIEND_SUCCESS = 'ADD_FRIEND_SUCCESS';
export const ADD_FRIEND_FAILURE = 'ADD_FRIEND_FAILURE';

export const GET_ALL_FRIENDS_REQUEST = 'GET_ALL_FRIENDS_REQUEST';
export const GET_ALL_FRIENDS_SUCCESS = 'GET_ALL_FRIENDS_SUCCESS';
export const GET_ALL_FRIENDS_FAILURE = 'GET_ALL_FRIENDS_FAILURE';

export const REMOVE_FRIEND_REQUEST = 'REMOVE_FRIEND_REQUEST';
export const REMOVE_FRIEND_SUCCESS = 'REMOVE_FRIEND_SUCCESS';
export const REMOVE_FRIEND_FAILURE = 'REMOVE_FRIEND_FAILURE';

export const GET_MUTUAL_FRIENDS_REQUEST = 'GET_MUTUAL_FRIENDS_REQUEST';
export const GET_MUTUAL_FRIENDS_SUCCESS = 'GET_MUTUAL_FRIENDS_SUCCESS';
export const GET_MUTUAL_FRIENDS_FAILURE = 'GET_MUTUAL_FRIENDS_FAILURE';



// Message types
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const SET_MESSAGES = 'SET_MESSAGES';

export const FETCH_MESSAGES_FROM_SENDER_REQUEST = 'FETCH_MESSAGES_FROM_SENDER_REQUEST';
export const FETCH_MESSAGES_FROM_SENDER_SUCCESS = 'FETCH_MESSAGES_FROM_SENDER_SUCCESS';
export const FETCH_MESSAGES_FROM_SENDER_FAILURE = 'FETCH_MESSAGES_FROM_SENDER_FAILURE';

export const FETCH_MESSAGES_FROM_RECEIVER_REQUEST = 'FETCH_MESSAGES_FROM_RECEIVER_REQUEST';
export const FETCH_MESSAGES_FROM_RECEIVER_SUCCESS = 'FETCH_MESSAGES_FROM_RECEIVER_SUCCESS';
export const FETCH_MESSAGES_FROM_RECEIVER_FAILURE = 'FETCH_MESSAGES_FROM_RECEIVER_FAILURE';





